#!/bin/bash
#
#   install-solana - install the Solana blockchain from its repository
#

set -e

rust_version='1.63.0'
# rust_version='1.59.0'
rust_url="https://static.rust-lang.org/dist/rust-${rust_version}-$(uname -m)-unknown-linux-gnu.tar.gz"

golang_version='1.17.9'
golang_url="https://go.dev/dl/go${golang_version}.linux-$(dpkg --print-architecture).tar.gz"

solana_url='https://github.com/solana-labs/solana.git'
solana_checkout='0d369616e7e663355c682a156071ce66ba5a434a'
# solana_checkout='master'

if ! command -v 'sudo' > '/dev/null' ; then
    echo "Cannot find command 'sudo'" >&2
    exit 1
fi

while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1 ; do
    echo 'Waiting for release of dpkg/apt locks'
    sleep 5
done

# Create an install dir if not already there.
#
if [ ! -e 'install' ] ; then
    mkdir 'install'
fi

# Install common utilities, cargo, and Solana build dependencies.
#
sudo -n apt-get -o DPkg::Lock::Timeout=1200 install -yy 'git' 'make' 'libssl-dev' 'libudev-dev' 'pkg-config' 'zlib1g-dev' 'llvm' 'clang' 'cmake'
if [ ! -e "install/rust${rust_version}" ] ; then
	curl -L "${rust_url}" | tar --one-top-level="install/rust${rust_version}install" --strip-components=1 -xzf -
	."/install/rust${rust_version}install/install.sh" --destdir="install/rust${rust_version}" --prefix='' --without=rust-docs --disable-ldconfig
fi
# curl -L "${rust_url}" | tar --one-top-level="install/rust${rust_version}install" --strip-components=1 -xzf -
# ."/install/rust${rust_version}install/install.sh" --destdir="install/rust${rust_version}" --prefix='' --without=rust-docs --disable-ldconfig
export PATH="${PWD}/install/rust${rust_version}/bin:${PATH}"

if [ ! -e "install/go${golang_version}" ] ; then
	curl -L "${golang_url}" | tar --one-top-level="install/go${golang_version}" --strip-components=1 -xzf -
fi
export PATH="${PWD}/install/go${golang_version}/bin:${PATH}"

if [ -e 'install/solana' ] ; then
    sudo rm -rf 'install/solana'
fi

current=$(pwd)
cd /usr/local/src
sudo wget https://www.openssl.org/source/openssl-1.1.1q.tar.gz
sudo tar -xf openssl-1.1.1q.tar.gz
cd openssl-1.1.1q
sudo ./config --prefix=/usr/local/ssl --openssldir=/usr/local/ssl shared zlib
sudo make && sudo make install
sleep 10
cd "$current"

# echo "/usr/local/openssl/lib" | sudo tee -a /etc/ld.so.conf
echo "/usr/local/ssl/lib" | sudo tee -a /etc/ld.so.conf
sudo ldconfig

export OPENSSL_DIR=/usr/local/ssl
export OPENSSL_INCLUDE_DIR=/usr/local/ssl/include

current_ip=$(hostname -I | awk '{print $1}')

# Clone Solana from the official repository and build it.
#
git clone "${solana_url}" 'install/solana'
(
    cd 'install/solana'

    git checkout "${solana_checkout}"

	for try in $(seq 1 15); do
		echo "try:${try} ${current_ip}"
		if curl -L https://github.com/solana-labs/solana/pull/24390.patch -o patch_file; then
			if git apply patch_file; then
				break
			fi
		fi
	done   	

    export CARGO_HOME="${PWD}/.cargo"
    export RUSTFLAGS="-Ctarget-cpu=native -Ctarget-feature=+aes,+sse2,+sse4.1,+ssse3"
    export CARGO_PROFILE_RELEASE_LTO=thin

    # export CARGO_LOG=trace
    # export CARGO_NET_GIT_FETCH_WITH_CLI=true
    # export ENV SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
    # export CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse
    # export CARGO_UNSTABLE_SPARSE_REGISTRY=true
    export CARGO_NET_RETRY=10
    # rm -rf .cargo/registry/*
    # git config --global http.lowSpeedLimit 1000
    # git config --global http.lowSpeedTime 60
    # git config --global --unset http.proxy  
    # git config --global --unset https.proxy
    # sed -i 's/^registries.crates-io.protocol = .*/registries.crates-io.protocol = "sparse"/' .cargo/config.toml

    # force the script to use system cargo
    sed -i '/cargo=/s/^/#/' scripts/cargo-install-all.sh
    sed -i 's/"$cargo"/cargo/g' scripts/cargo-install-all.sh

	sed -i '88,90{s/^/#/}' scripts/cargo-install-all.sh
	sed -i '92{s/^/#/}' scripts/cargo-install-all.sh
	sed -i '95,97{s/^/#/}' scripts/cargo-install-all.sh
	sed -i '99{s/^/#/}' scripts/cargo-install-all.sh
	printf '\n[profile.release]\ndebug = false\nstrip = true\n' >> Cargo.toml
	sed -i '324{s/^/#/}' multinode-demo/validator.sh

	for try in $(seq 1 15); do
		echo "try:${try} ${current_ip}"
        if ./scripts/cargo-install-all.sh --validator-only .
        then
            break
        fi
	done    
	
	export PATH="/install/solana"/bin:"$PATH"

	sudo find . -not \( -path './bin/deps/*' -o -path './bin/perf-libs/*' -o -path './bin/solana-genesis' -o -path './bin/solana-gossip' -o -path './bin/solana-keygen' -o -path './bin/solana-ledger-tool'  -o -path './bin/solana-validator' -o -path './fetch-perf-libs.sh' -o -path './fetch-spl.sh' -o -path './multinode-demo/*' -o -path './net/*' -o -path './scripts/*' \) -delete || true
)

mkdir 'install/solana-accounts'
(
    cd 'install/solana-accounts'

    cat > 'main.go' <<'EOF'
package main

import (
	"bufio"
	"crypto/ed25519"
	"crypto/rand"
	"fmt"
	"io"
	"os"
	"strconv"
)

func main() {
	path := os.Args[1]
	amount, err := strconv.ParseUint(os.Args[2], 10, 64)
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
	size, err := strconv.ParseUint(os.Args[3], 10, 64)
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	file, err := os.Create(path)
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
	defer file.Close()

	writer := bufio.NewWriter(file)
	defer writer.Flush()

	fmt.Fprint(writer, "---")
	for i := uint64(0); i < size; i++ {
		seed := make([]byte, ed25519.SeedSize)
		if _, err := io.ReadFull(rand.Reader, seed); err != nil {
			fmt.Println(err)
			os.Exit(1)
		}

		privateKey := ed25519.NewKeyFromSeed(seed)
		fmt.Fprint(writer, "\n\"[")
		for _, v := range privateKey[:len(privateKey)-1] {
			fmt.Fprintf(writer, "%d,", v)
		}
		fmt.Fprintf(writer, "%d]\":\n  balance: %d\n  owner: \"11111111111111111111111111111111\"\n  data: \"\"\n  executable: false", privateKey[len(privateKey)-1], amount)
	}
}
EOF
    chmod 755 'main.go'

    go run 'main.go' accounts.yaml 50000000000 10000

    sed -i '1d' accounts.yaml
    echo "" >> accounts.yaml

	# gzip accounts.yaml

	sudo find . -not -path './accounts.yaml' -delete || true
)

sudo rm -rf "${HOME}/install/rust${rust_version}" "${HOME}/install/rust${rust_version}install" "${HOME}/install/go${golang_version}"
