#!/bin/bash
#
#   install-diablo - install diablo
#

set -e

# golang_version='1.21.8'
golang_version='1.17.8'
golang_url="https://go.dev/dl/go${golang_version}.linux-$(dpkg --print-architecture).tar.gz"

diablo_url='https://github.com/NatoliChris/diablo-benchmark.git'
diablo_checkout='aec'

if ! command -v 'sudo' > '/dev/null' ; then
    echo "Cannot find command 'sudo'" >&2
    exit 1
fi

while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1 ; do
    echo 'Waiting for release of dpkg/apt locks'
    sleep 5
done

# Create an install dir if not already there.
#
if [ ! -e 'install' ] ; then
    mkdir 'install'
fi

# Install common utilities as well as golang.
#
sudo -n apt-get -o DPkg::Lock::Timeout=1200 install -yy 'git' 'make' 'gcc'
if [ ! -e "install/go${golang_version}" ] ; then
	curl -L "${golang_url}" | tar --one-top-level="install/go${golang_version}" --strip-components=1 -xzf -
fi
export PATH="${PWD}/install/go${golang_version}/bin:${PATH}"

if [ -e 'install/diablo' ] ; then
    sudo rm -rf 'install/diablo'
fi

# Clone Diablo from the official repository and build it.
#
git clone "${diablo_url}" 'install/diablo'
(
    cd 'install/diablo'

    git checkout "${diablo_checkout}"

    # Avoid modification outside of this repository.
    # This is important because some other installed software could use
    # different versions of Go.
    #
    export GOPATH="${PWD}/go"

    # cp /fixes/net/tcp* communication/
    # cp /fixes/net/net.go core/

    go mod tidy

    # make reqs
    # echo "HERE"
    # GO111MODULE=off go get -v golang.org/x/lint/golint
    go get -d -v golang.org/x/lint/golint
    # echo "HERE1"
	go mod download
    # echo "HERE2"
	go mod vendor
    # echo "HERE3"

    make diablo

    go clean --cache

    sudo find . -not \( -path './diablo' -or -path './move-contracts/*' -or -path './solidity-contracts/*' -or -path './teal-contracts/*' \) -delete || true
)

sudo rm -rf "${HOME}/install/go${golang_version}"